services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=webui_lf
      - POSTGRES_PASSWORD=Lfrag!25Secured
      - POSTGRES_DB=openwebui
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webui_user -d openwebui"]
      interval: 5s
      timeout: 5s
      retries: 10

  open-webui:
    image: ghcr.io/littelfuse-ssamuel/open-webui-lf:lf-latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://webui_lf:Lfrag!25Secured@postgres:5432/openwebui
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key-here}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}

      # External Document Loader Configuration
      - PDF_EXTRACT_IMAGES=true
      - RAG_DOCUMENT_LOADER_ENGINE=external
      - EXTERNAL_DOCUMENT_LOADER_URL=http://extloader:8000
      - EXTERNAL_DOCUMENT_LOADER_API_KEY=${EXTERNAL_DOCUMENT_LOADER_API_KEY:-your-api-key-here}

      # SSL Configuration
      - SSL_CERT_FILE=${SSL_CERT_FILE:-}
      - REQUESTS_CA_BUNDLE=${REQUESTS_CA_BUNDLE:-}
      - PORT=8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      extloader:
        condition: service_started
      

  extloader:
    image: ghcr.io/littelfuse-ssamuel/open-webui-extloader:lf-latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_CERT_FILE=${SSL_CERT_FILE:-}
      - REQUESTS_CA_BUNDLE=${REQUESTS_CA_BUNDLE:-}
      - PORT=8000
      - DOCUMENT_INTELLIGENCE_ENDPOINT=${DOCUMENT_INTELLIGENCE_ENDPOINT}
      - DOCUMENT_INTELLIGENCE_KEY=${DOCUMENT_INTELLIGENCE_KEY}
    restart: unless-stopped

volumes:
  postgres_data: